language: objective-c
osx_image: xcode7.1
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace mapcache-ios.xcworkspace -scheme mapcache-ios -sdk iphonesimulator9.1 -destination "OS=9.1,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO | xcpretty
  # TODO
  #- xcodebuild test -workspace mapcache-ios.xcworkspace -scheme mapcache-ios -sdk iphonesimulator9.1 -destination "OS=9.1,name=iPhone 6s" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
